/** Build step: bake the latest field notes into the bundle.
 *
 *  The rail used to list the workspace's own analyses, which the screen
 *  beneath it was already showing. This puts something there the page does
 *  not have: the newest posts from growthterminal.io/blog.
 *
 *  Why a build step and not a fetch in the browser. The blog is served from
 *  growthterminal.io and the portal from app.growthterminal.io, which are
 *  different origins, and the marketing site sends no access control header,
 *  so a runtime fetch is refused before it starts. Cloudflare Pages runs this
 *  command on every deploy with ordinary network access, so the list refreshes
 *  whenever the portal ships. That is the honest bound on freshness: as recent
 *  as the last deploy, not as recent as the last post.
 *
 *  This must never fail a deploy. The blog being slow, moved, or briefly down
 *  is not a reason to stop shipping the product, so every failure path leaves
 *  the previously generated file exactly as it was and exits zero. The file is
 *  committed for that reason: there is always something real to render.
 */
import { writeFileSync, existsSync } from 'node:fs'

const FEED = 'https://growthterminal.io/blog/feed.xml'
const OUT = 'src/lib/blogPosts.ts'
const COUNT = 4
const TIMEOUT_MS = 8000

/* Same rule as lib/sanitize.ts, applied here so a dash in a post title cannot
   reach the bundle. Written as escapes so this file passes the source scan. */
const EM = '\u2014'
const EN = '\u2013'
const RANGE = new RegExp('(\\d)\\s*[' + EN + EM + ']\\s*(\\d)', 'g')
const DASH = new RegExp('\\s*[' + EN + EM + ']\\s*', 'g')
const clean = (s) => s
  .replace(RANGE, '$1-$2')
  .replace(DASH, ', ')
  .replace(/,\s*,+/g, ',')
  .replace(/\s+,/g, ',')
  .replace(/^,\s*/, '')
  .replace(/,\s*$/, '')

/* RSS carries text as entities or as CDATA depending on the generator, and
   this feed uses both. */
const decode = (s) => s
  .replace(/^<!\[CDATA\[/, '').replace(/\]\]>$/, '')
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&apos;/g, "'")
  .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(+d))
  .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCharCode(parseInt(h, 16)))
  .replace(/&amp;/g, '&')
  .trim()

const tag = (block, name) => {
  const m = block.match(new RegExp('<' + name + '[^>]*>([\\s\\S]*?)</' + name + '>'))
  return m ? clean(decode(m[1])) : ''
}

function parse(xml) {
  return xml.split('<item>').slice(1)
    .map((b) => {
      const end = b.indexOf('</item>')
      return end === -1 ? b : b.slice(0, end)
    })
    .map((b) => {
      const when = new Date(tag(b, 'pubDate'))
      return {
        title: tag(b, 'title'),
        url: tag(b, 'link'),
        date: isNaN(when.getTime()) ? '' : when.toISOString().slice(0, 10),
        category: tag(b, 'category')
      }
    })
    /* A post with no title or no link is not renderable, and a half drawn row
       is worse than one fewer row. */
    .filter((p) => p.title && /^https?:\/\//.test(p.url))
    .slice(0, COUNT)
}

const HEAD = `/** Generated by scripts/fetch-blog.mjs on every build. Do not edit by hand.
 *
 *  Committed so the rail always has something real to render even when the
 *  build machine cannot reach the feed. See the script for why this is a build
 *  step rather than a fetch in the browser. */

export interface BlogPost { title: string; url: string; date: string; category: string }

export const BLOG_URL = 'https://growthterminal.io/blog'

export const BLOG_POSTS: BlogPost[] = `

function write(posts) {
  writeFileSync(OUT, HEAD + JSON.stringify(posts, null, 2) + '\n')
}

async function main() {
  if (!existsSync('src/lib')) {
    console.log('blog feed: no src/lib, skipping.')
    return
  }
  const ctl = new AbortController()
  const timer = setTimeout(() => ctl.abort(), TIMEOUT_MS)
  try {
    const res = await fetch(FEED, { signal: ctl.signal })
    if (!res.ok) throw new Error('HTTP ' + res.status)
    const xml = await res.text()
    /* The portal's own host answers unknown paths with the app shell at status
       200, and a misconfigured redirect elsewhere could do the same, so status
       is not proof. Only something that actually looks like the feed counts. */
    if (!/<rss[\s>]/.test(xml) || xml.indexOf('<item>') === -1) {
      throw new Error('response is not an RSS feed')
    }
    const posts = parse(xml)
    if (!posts.length) throw new Error('feed parsed to zero usable items')
    write(posts)
    console.log(`blog feed: ${posts.length} post(s) baked, newest ${posts[0].date}.`)
  } catch (e) {
    console.log(`blog feed: keeping the committed list (${e.message}).`)
  } finally {
    clearTimeout(timer)
  }
}

main()
