/** Generated by scripts/fetch-blog.mjs on every build. Do not edit by hand.
 *
 *  Committed so the rail always has something real to render even when the
 *  build machine cannot reach the feed. See the script for why this is a build
 *  step rather than a fetch in the browser. */

export interface BlogPost { title: string; url: string; date: string; category: string }

export const BLOG_URL = 'https://growthterminal.io/blog'

export const BLOG_POSTS: BlogPost[] = [
  {
    "title": "Serious Advisors Keep a Miss Ledger, Not a Highlight Reel",
    "url": "https://growthterminal.io/blog/2026-08-14-serious-advisors-keep-a-miss-ledger-not-a-highlight-reel",
    "date": "2026-08-14",
    "category": "strategy"
  },
  {
    "title": "Point Forecasts Create False Promises and Bad Decisions",
    "url": "https://growthterminal.io/blog/2026-08-13-point-forecasts-create-false-promises-and-bad-decisions",
    "date": "2026-08-13",
    "category": "forecasting"
  },
  {
    "title": "Your Wins Don’t Prove Skill. Your Misses Do.",
    "url": "https://growthterminal.io/blog/2026-08-12-your-wins-dont-prove-skill-your-misses-do",
    "date": "2026-08-12",
    "category": "strategy"
  },
  {
    "title": "Autonomous Agents Turn Advisory Into a Measured Factory",
    "url": "https://growthterminal.io/blog/2026-08-11-autonomous-agents-turn-advisory-into-a-measured-factory",
    "date": "2026-08-11",
    "category": "agents"
  }
]
